apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-project-frontend
  #annotations:
    #backstage.io/techdocs-ref: url:https://github.com/backstage123/node-repo/tree/master
    
spec:
  type: service
  owner: user:default/guest
  lifecycle: experimental
  system: test-system
  dependsOn: 
    - component:test-project-backend
  consumesApis: 
    - api:test-api
