apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test-system
  #annotations:
    #backstage.io/techdocs-ref: url:https://github.com/backstage123/node-repo/tree/master
    
spec:
  type: service
  owner: user:default/guest
  lifecycle: experimental
  #dependsOn: 
    #- component:etesoro-backend
